image: debian

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

before_script:
# install sysrepo-plugin-system dependencies
  - apt-get update
  - apt-get -y install clang cmake git libpcre2-dev libsystemd-dev libcmocka0 libcmocka-dev valgrind
  - apt-get -y install python3 python3-pip
  - git clone https://github.com/CESNET/libyang.git
  - git clone https://github.com/sysrepo/sysrepo.git
  - git clone https://github.com/telekom/sysrepo-plugins-common.git
  - git clone https://github.com/sartura/umgmt.git
  - cd libyang; git checkout devel; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../../
  - cd sysrepo; git checkout devel; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../../
  - cd sysrepo-plugins-common; git submodule init; git submodule update; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../..
  - cd umgmt; git submodule init; git submodule update;  mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../..
  - pip3 install libyang
  - pip3 install Jinja2
# install robotframework-sysrepolibrary dependencies
  - pip3 install --upgrade pip setuptools wheel build tox


build:sysrepo_plugin_system:
  stage: build

  script:
    - mkdir build
    - cmake -S . -B build/ -DSYSTEMD_IFINDEX=1 -DENABLE_BUILD_TESTS=ON -DCMAKE_C_COMPILER=clang
    - cmake --build build/
  
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/


build:default:
  stage: build
  needs: ["build:sysrepo_plugin_system"]
  script:
    - python3 -m pip install .


test:default:
  stage: test
  needs: ["build:default"]
  script:
    - cd examples
    - robot .
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - examples/


test:tox:
  stage: test
  needs: ["build:default"]
  script:
    - tox
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - .tox/**/*.log

