image: debian

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

before_script:
# install sysrepo-plugin-system dependencies
  - apt-get update
  - apt-get -y install clang cmake git libpcre2-dev libsystemd-dev libcmocka0 libcmocka-dev valgrind
  - apt-get -y install python3 python3-pip
  - git clone https://github.com/CESNET/libyang.git
  - git clone https://github.com/sysrepo/sysrepo.git
  - cd libyang; git checkout devel; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../../
  - cd sysrepo; git checkout devel; mkdir build; cd build; cmake .. -DCMAKE_C_COMPILER=clang; make -j install; cd ../../
  - pip3 install libyang Jinja2 rpaframework


build:default:
  stage: build
  script:
    - python3 -m pip install .[docs,tests]


test:default:
  stage: test
  needs: ["build:default"]
  script:
    - cd examples
    - robot .
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - examples/


test:tox:
  stage: test
  needs: ["build:default"]
  script:
    - tox
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - .tox/**/*.log

